services:
  # PHP and Apache, described in Dockerfile
  php-apache:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfiles/PhpApache
    volumes:
      - ./www:/var/www/
    ports:
      - 8000:80

  # MySQL database installation
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfiles/Database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university
      MYSQL_USER: admin
      MYSQL_PASSWORD: heslo
    ports:
      - 9906:3306

  # phpMyAdmin installation for database management
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
